version: '3.8'

services:
  my-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4002:4001"  # Use host port 4002 mapped to container port 4001
    environment:
      - IB_HOST=host.docker.internal
      - IB_PORT=4001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
